### ISSUE TITLE
Add explicitly a message in order to process for fonctional test

### ISSUE THREAD

**Issue by fpondepeyre** [zenstruck/messenger-test#13]
Hello, thank you for your amazing lib.
Is there a way to explicitly add a message in a queue in order to process this message ?
In my case, an other service push a message in messenger. My main app receive and process the message. I would like to realize a functional test (no access to the first app, no shared rabbitmq in ci). I am no way to populate the queue without special hack for test.

for exemple, i would like to do this with phpunit:

```
$this->messenger()->queue()->addMessage(new MyMessage('42')); 
$this->messenger()->process();
//check in db|file|other the process was successfully executed
```

Do you think it's the right way or completely dumby ?

Thank you for your help !

[EDIT]

It's work with

```
$transport = self::$container->get('messenger.transport.my_message');
$transport->send(new Envelope($new MyMessage(42), [new AmqpStamp("my_message")]));
$this->messenger('my_message')->queue()->assertContains(MyMessage::class, 1);
$this->messenger('my_message')->process();
```

**Comment by kbond** [comment]
I was going to suggest what you did in your edit. `TestTransport::send()` is marked as internal - maybe I should remove that?

**Comment by fpondepeyre** [comment]
Thank you,  but i don't know all about the impact of this change... you are the expert !

**Comment by kbond** [comment]
No impact really, I just marked everything that I didn't expect to be used by end-users as `@internal`.

**Comment by kbond** [comment]
@fpondepeyre, what do you think of #14?
