### ISSUE TITLE
`TestTransport::send()`: don't always test serialization

### ISSUE THREAD

**Issue by nikophil** [zenstruck/messenger-test#33]
Hello,

it would be very nice to make conditional the [test of the serialization](https://github.com/zenstruck/messenger-test/blob/1.x/src/Transport/TestTransport.php#L228-L229) when we send it to the transport. Maybe at the transport level, the same way it is done for catching the exceptions.

The reason is when you send messages to an external system, you don't need to know how to deserialize it. 

I can provide a PR if needed.

**Comment by kbond** [comment]
This makes sense.

> Maybe at the transport level, the same way it is done for catching the exceptions.

That's what I was thinking as well: `test://?serialize=false`

Sure, I'd appreciate a PR!
