### ISSUE TITLE
Contradictory default option value for support_delay_stamp

### ISSUE THREAD

**Issue by NicolasMurillon** [zenstruck/messenger-test#68]
## Description
In `TestTransportFactory`, when creating a transport, if `support_delay_stamp` is not set in the dsn, this option will be set to true at line 58.

However,  in `TestTransport`, `support_delay_stamp` is set to false in the default options. When merging the array at line 85, the option coming from `TestTransportFactory` takes precedence.

## Proposed solution
Change the default value in `TestTransportFactory`, or update the README to tell that `support_delay_stamp` is true by default and needs to be overridden in the dsn

**Comment by nikophil** [comment]
hi @NicolasMurillon 

thanks for this issue. I'll update the default to set it to false everywhere
