### ISSUE TITLE
DoctrineTransport table dropped when running `doctrine:schema:update`

### ISSUE THREAD

**Issue by bendavies** [zenstruck/messenger-test#78]
Hi,

In CI, we run
```sh
APP_ENV=test bin/console doctrine:schema:update --dump-sql --complete --ansi --no-interaction
```
to ensure that our schema in sync with the database.
However this produced `DROP TABLE messenger_messages` when using this bundle because this check fails, as the transport is actually `Zenstruck\Messenger\Test\Transport\TestTransport`

https://github.com/symfony/symfony/blob/9b323c6866078f1bc761d7cc34297c41815108d3/src/Symfony/Bridge/Doctrine/SchemaListener/MessengerTransportDoctrineSchemaListener.php#L39

Is there a way to fix this, apart from running with `APP_ENV=prod` instead?

Thans!

**Comment by kbond** [comment]
Hmm, in your test env, could you create a dummy/unused transport that uses doctrine?

**Comment by bendavies** [comment]
ahh ok, a single one NOT using `test://`?

ok i'll try that!

**Comment by kbond** [comment]
> a single one NOT using test://?

yep, exactly!

**Comment by bendavies** [comment]
that'll work! thank
