### ISSUE TITLE
Testing Serialization completly

### ISSUE THREAD

**Issue by jaugustin** [zenstruck/messenger-test#86]
Hello,

Thanks @kbond for this great tooling. We found an issue with the serialization testing.

The library test that a message can be serialized and unserialized, but the unserialized version is not used when processing.

We had a issue where the unserialized version was fine but the unserialized object was missing a mandatory property witch made the process fail in real environment but not in the test.

Do you accept a MR that will use the unserialized version of the message when processing ?

**Comment by nikophil** [comment]
hi @jaugustin 

this sounds legit, I guess

**Comment by kbond** [comment]
Closed in #87
