### ISSUE TITLE
Additional handler arguments

### ISSUE THREAD

**Issue by norkunas** [zenstruck/messenger-test#89]
I've setup a middleware to inject retry count argument into my message handlers (https://symfony.com/doc/current/messenger.html#additional-handler-arguments) and it works.
But my tests are failing when using test bus because it doesn't know about this middleware.

Would it be possible to support this?

**Comment by nikophil** [comment]
Hi @norkunas 

I didn't know about this feature in messenger! thanks!

but it should work out of the box, this lib has no effect on how messenger / handlers / stamps deal with each others.
I just tested it, and confirm it works.

Maybe you're using a bus which does not have this middleware?

**Comment by norkunas** [comment]
Hmm, I have only a single bus on which I've applied it, and then it started to fail :/

**Comment by nikophil** [comment]
The problem might not be the "additional argument" feature but maybe something around the middlewares 🤔
Could you share some code, please?

**Comment by norkunas** [comment]
Oh, now I know. I need to add the argument to the all handlers, argument becomes non-optional :disappointed: 
Will have to inspect the message __invoke method for defined arguments and return based on that.
Thank you

**Comment by norkunas** [comment]
Looks like there is no easy way to get the handler to inspect in the middleware :thinking:

**Comment by nikophil** [comment]
I'm not sure to understand what you mean 🤔

**Comment by norkunas** [comment]
I mean about:
> Will have to inspect the message __invoke method for defined arguments and return based on that.

That I didn't find a way to do this, so only viable solution is to defined the argument in all my message handlers which sucks :thinking:
