### ISSUE TITLE
It is possible to test MessengerMessage ?

### ISSUE THREAD

**Issue by Radio-Skonto** [zenstruck/messenger-test#93]
```
class UploadArtworkTest extends KernelTestCase
{
    use InteractsWithMessenger;
    public function testSomething(): void
    {
        $kernel = self::bootKernel();
        $this->assertSame('test', $kernel->getEnvironment());
        $this->transport('async')->queue()->assertEmpty();

        $message = new UpdateArtworkAPIMessage('https://www.song-data.lv/artwork/bryan-adams.jpg');
        $this->transport('async')->send($message);
        $this->transport('async')->queue()->assertCount(1);

        $this->transport('async')->process();

    }
}
```
When i process message i din't know what happens inside MessageHandler.
I want to test MessengerHandler but know ?

**Comment by nikophil** [comment]
Hi @Radio-Skonto 

I'm not sure to fully understand what you want to test?

**Comment by Radio-Skonto** [comment]
Hi @nikophil 

I want to test MessageHandler.
For example i have message
```
<?php

namespace App\Artwork\Application\Message;

class UpdateArtworkAPIMessage
{

    public function __construct(
       private readonly string $songURL,
    ) {
    }

    public function getSongURL(): string
    {
        return $this->songURL;
    }
}
```
and this messageHandler
```
<?php

namespace App\Artwork\Application\MessageHandler;

use App\Artwork\Application\Message\UpdateArtworkAPIMessage;
use App\Entity\PlayNow;
use App\Repository\PlayNowRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Component\Messenger\Attribute\AsMessageHandler;

#[AsMessageHandler]
class UpdateArtworkAPIMessageHandler
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        private readonly LoggerInterface $logger,
        private readonly PlayNowRepository $playNowRepository,
    ) {
    }

    public function __invoke(UpdateArtworkAPIMessage $message)
    {
       /// I WANT TO TEST CODE BELOW IN MESSAGEHANDLER
        $songURLPath = explode('/', $message->getSongURL());
        if (!is_array($songURLPath)) {
            $errorMessage = 'Song URL isn\'t correct - '.$message->getSongURL();
            $this->logErrorAndExit($errorMessage);
        }
        $songArtistAndTitleFilename = end($songURLPath);
............
```

I want to execute method invoke and test it - however it's return void = nothing

**Comment by nikophil** [comment]
After the call of ` $this->transport('async')->process();`, what you should do is:
- check that the message is in `$transport->acknowledged()` (success) or `$transport->rejected()` (failure)
- check the potential side effect your handler did (maybe something is in database? an external api has been called....)

And maybe you should unit test the class `UpdateArtworkAPIMessageHandler`. But this is not the purpose of this library.

I'm closing the issue, don't hesitate to reopen it for further questions.

**Comment by Radio-Skonto** [comment]
Thank you very much for answer - I think need to update readme with -> the purpose of this library. Otherwise i will ask stupid question.... Sorry for that

**Comment by Radio-Skonto** [comment]
@nikophil  BTW -> purpose of this library is only Transport check? Messages send and successfully processed, correct ?

**Comment by nikophil** [comment]
The readme says:
> Assertions and helpers for testing your symfony/messenger queues.
This library provides a TestTransport that, by default, intercepts any messages sent to it. You can then inspect and assert against these messages. Sent messages are serialized and unserialized as an added check.
The transport also allows for processing these queued messages.

which seems very clear to me, but don't hesitate to improve this :)
